<a href="https://colab.research.google.com/github/DurkadeviGanesanMCA/State-wise-GST-Revenue-Analysis-in-India-Using-Python/blob/main/State_wise_GST_Revenue_Analysis_in_India_Using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Stage 1**

## ***State-wise-GST-Revenue-Analysis-in-India-Using-Python***

### **Business Objective**

Analyze GST tax collection data across Indian states and tax components to identify revenue trends, evaluate state-wise tax performance, and provide data-driven recommendations that support revenue planning, tax policy decisions, and improved tax compliance.

### **Analytical Objectives**


*   Measure the total GST collection across the available time period.

*   Compare GST collections across states and Union Territories.

*   Analyze trends in GST collection by month and year.
Identify the contribution of CGST, SGST, IGST, and Cess to total GST revenue.

*   Determine the top and bottom revenue-contributing states.

*   Analyze year-over-year (YoY) and month-over-month (MoM) growth in GST collections.

*   Identify seasonal patterns and revenue fluctuations.

*   Detect anomalies or unusually high/low GST collections.

### **Dataset Schema**

| **Column Name** | **Data Type**                               | **Description**                                                                  |
| --------------- | ------------------------------------------- | -------------------------------------------------------------------------------- |
| **id**          | Integer (`int64`)                           | Unique identifier for each GST collection record.                                |
| **date**        |  `object` *(convert to `datetime`)* | Date of GST collection. Used for monthly and yearly trend analysis.              |
| **state_name**  |  (`object`)                           | Name of the Indian State or Union Territory.                                     |
| **state_code**  |  (`int64`)                           | Official state or Union Territory code.                                          |
| **cgst**        |  (`float64`)                         | Central Goods and Services Tax (CGST) collected.                                 |
| **sgst**        |  (`float64`)                         | State Goods and Services Tax (SGST) collected.                                   |
| **igst**        |  (`float64`)                         | Integrated Goods and Services Tax (IGST) collected from interstate transactions. |
| **cess**        |  (`float64`)                         | GST Compensation Cess collected on specified goods and services.                 |

### **Tools And Technologies**
| **Category**                  | **Tool / Technology**      | **Purpose**                                                          |
| ----------------------------- | -------------------------- | -------------------------------------------------------------------- |
| **Programming Language**      | Python                     | Data analysis, data cleaning, feature engineering, and visualization |
| **Data Processing**           | Pandas                     | Data manipulation and analysis                                       |
| **Numerical Computing**       | NumPy                      | Numerical operations and calculations                                |
| **Data Visualization**        | Matplotlib                 | Static charts and graphs                                             |
| **Interactive Visualization** | Plotly *(Optional)*        | Interactive dashboards and                  |
| **Development Environment**   | Google Colab | Code development and analysis                                        |
| **Version Control**           | Git                        | Track project changes                                                |
| **Repository Hosting**        | GitHub                     | Store code, documentation, and project files                         |
| **Dataset Format**            | CSV                        | Source data format                                                   |
| **Documentation**             | Markdown (README.md)       | Project documentation and GitHub presentation                        |

### **Python Libraries Used**
| **Library**           | **Purpose**                              |
| --------------------- | ---------------------------------------- |
| `pandas`              | Data loading, cleaning, and manipulation |
| `numpy`               | Mathematical and numerical computations  |
| `matplotlib`          | Data visualization                       |
| `plotly` *(Optional)* | Interactive charts      |
| `Seaborn`              | data visualization library built on top of Matplotlib |

In [ ]:
# =====================================
# GST Tax Collection Analysis
# =====================================

#Import Python libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Data Loded From Github

url = "https://raw.githubusercontent.com/DurkadeviGanesanMCA/State-wise-GST-Revenue-Analysis-in-India-Using-Python/main/tax-collection-on-gst-portal.csv"

   id        date                   state_name  state_code  cgst  sgst  igst  \
0   0  2017-07-01  Andaman And Nicobar Islands          35  0.00  0.00  0.00
1   1  2017-07-01               Andhra Pradesh          28  2.60  2.59  4.32
2   2  2017-07-01            Arunachal Pradesh          12  0.00  0.00  0.00
3   3  2017-07-01                        Assam          18  0.02  0.02  0.21
4   4  2017-07-01                        Bihar          10  0.02  0.02  0.47

   cess
0  0.00
1  0.00
2  0.00
3  0.07
4  0.04

In [ ]:
#Csv file is converted to datafarme with pandas

df = pd.read_csv(url)

# **Initial Exploratory Data Analysis**

In [ ]:
# displaying first 5 rows
df.head()

,id,date,state_name,state_code,cgst,sgst,igst,cess
0,0,2017-07-01,Andaman And Nicobar Islands,35,0.00,0.00,0.00,0.00
1,1,2017-07-01,Andhra Pradesh,28,2.60,2.59,4.32,0.00
2,2,2017-07-01,Arunachal Pradesh,12,0.00,0.00,0.00,0.00
3,3,2017-07-01,Assam,18,0.02,0.02,0.21,0.07
4,4,2017-07-01,Bihar,10,0.02,0.02,0.47,0.04

In [ ]:
#To evaluate data health, check for missing values, and monitor memory consumption.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3570 entries, 0 to 3569
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          3570 non-null   int64
 1   date        3570 non-null   object
 2   state_name  3570 non-null   object
 3   state_code  3570 non-null   int64
 4   cgst        3570 non-null   float64
 5   sgst        3570 non-null   float64
 6   igst        3570 non-null   float64
 7   cess        3570 non-null   float64
dtypes: float64(4), int64(2), object(2)
memory usage: 223.3+ KB

In [ ]:
#to understand the attribute and to check  the column labels
df.columns

Index(['id', 'date', 'state_name', 'state_code', 'cgst', 'sgst', 'igst',
       'cess'],
      dtype='object')

In [ ]:
#to understand quick statistical summary of your DataFrame
df.describe()

,id,state_code,cgst,sgst,igst,cess
count,3570.000000,3570.000000,3570.000000,3570.000000,3570.000000,3570.000000
mean,1784.500000,23.005322,620.185992,802.641053,905.849599,299.318499
std,1030.714558,20.384074,1062.552636,1288.250475,1453.390986,1011.813650
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,892.250000,10.000000,19.367500,27.585000,78.552500,0.190000
50%,1784.500000,19.000000,218.605000,331.610000,299.200000,10.550000
75%,2676.750000,31.000000,812.567500,1068.632500,1103.485000,431.565000
max,3569.000000,99.000000,10263.180000,11729.430000,13430.360000,32828.360000

In [ ]:
#To Check The dataType
df.dtypes

id              int64
date           object
state_name     object
state_code      int64
cgst          float64
sgst          float64
igst          float64
cess          float64
dtype: object

In [ ]:
#To Check Duplicate Records
df.duplicated().sum()

np.int64(0)

In [ ]:
# To Identify Null Values
df.isnull().sum()

id            0
date          0
state_name    0
state_code    0
cgst          0
sgst          0
igst          0
cess          0
dtype: int64